stages:
  - prepare
  - audit
  - lint
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "16.1"
    file: '/npm/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "16.1"
    file: '/npm/audit.yml'
  - project: 'intern/runner-templates'
    ref: "16.1"
    file: '/npm/eslint.yml'

  # Publish
  - project: 'intern/runner-templates'
    ref: "16.1"
    file: '/npm/publish.yml'
