stages:
  - prepare
  - lint
  - publish

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "9.6"
    file: '/npm/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "9.6"
    file: '/npm/audit.yml'
  - project: 'intern/runner-templates'
    ref: "9.6"
    file: '/npm/eslint.yml'

  # Publish
  - project: 'intern/runner-templates'
    ref: "9.6"
    file: '/npm/publish.yml'
